#YML to map a volume to container called persistent volume docker
version: '3'
services:
  jenkins:
    container_name: jenkins
    image: jenkins/jenkins:lts-jdk11
    ports:
      - "8080:8080"
    volumes:
      - "/home/ec2-user/jenkins_home:/var/jenkins_home"